name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"
      
      - name: Get Build Date
        id: currentbuilddate
        run: echo "::set-output name=currentbuilddate::${{ secrets.BUILD_DATE }}"
      
      - name: Get Build Number
        id: currentbuildnumber
        run: echo "::set-output name=currentbuild::${{ secrets.BUILD_NUMBER }}"
      
      - name: Get Current Date
        id: currentdate
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Echo variables
        run: echo ${{ steps.currentbuilddate.outputs.currentbuilddate }} and ${{ steps.currentdate.outputs.date }}
      
      - name: Generate Build Number
        id: buildnumber
        if: ${{ steps.currentbuilddate.outputs.currentbuilddate == steps.currentdate.outputs.date }}
        run: echo "::set-output name=buildnumber::${{steps.currentbuildnumber.outputs.currentbuild + 1}}"

      - name: GitHub Login
        shell: bash
        run: gh auth login --with-token <<< ${{ secrets.PAT }}

      - name: Set Build Date Secret
        shell: bash
        run: gh secret set BUILD_DATE --body ${{ steps.currentdate.outputs.date }} --repo ${{ github.repository }}

      - name: Set Build Number Secret
        shell: bash
        run: gh secret set BUILD_NUMBER --body ${{ steps.currentbuildnumber.outputs.currentbuild }} --repo ${{ github.repository }}
      
      - name: Output Version
        id: version
        run: echo "::set-output name=version::v${{ steps.currentdate.outputs.date }}.${{ steps.currentbuildnumber.outputs.currentbuild }}"
      
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.ts"]'
        env:
          VERSION: ${{ steps.version.outputs.version }}
     
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_06E32631E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/ui"
          api_location: "/functions"
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_06E32631E }}
          action: "close"
